services:
  - type: web
    name: tmc-meredian
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
